#!/usr/bin/env python3
"""Generate ES-DE custom find rules pointing to nix-built emulators."""
import os
import sys

def main():
    result_dir = os.path.realpath(sys.argv[1]) if len(sys.argv) > 1 else os.path.realpath("result")
    output_dir = os.path.expanduser("~/ES-DE/custom_systems")
    output_path = os.path.join(output_dir, "es_find_rules.xml")
    ryujinx_bin = os.path.expanduser("~/.local/share/ryujinx-app/Ryujinx.app/Contents/MacOS/Ryujinx")

    emulators = {
        "RETROARCH": f"{result_dir}/Applications/RetroArch.app/Contents/MacOS/RetroArch",
        "AZAHAR": f"{result_dir}/Applications/azahar.app/Contents/MacOS/azahar",
        "DOLPHIN": f"{result_dir}/Applications/Dolphin.app/Contents/MacOS/Dolphin",
        "PCSX2": f"{result_dir}/Applications/PCSX2.app/Contents/MacOS/PCSX2",
        "CEMU": f"{result_dir}/Applications/Cemu.app/Contents/MacOS/Cemu",
        "RYUJINX": ryujinx_bin,
    }

    lines = [
        '<?xml version="1.0"?>',
        '<!-- Generated by schemulator - regenerated on each make all -->',
        '<ruleList>',
    ]
    for name, path in emulators.items():
        lines += [
            f'  <emulator name="{name}">',
            '    <rule type="staticpath">',
            f'      <entry>{path}</entry>',
            '    </rule>',
            '  </emulator>',
        ]
    lines += [
        '  <core name="RETROARCH">',
        '    <rule type="corepath">',
        f'      <entry>{result_dir}/cores</entry>',
        '    </rule>',
        '  </core>',
        '</ruleList>',
    ]

    os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Written to {output_path}")


if __name__ == "__main__":
    main()
