#!/usr/bin/env python3
"""Generate ES-DE find rules + platform-specific es_systems.xml.

Two outputs, both written to ~/ES-DE/custom_systems/:

  1. es_find_rules.xml — staticpath entries pointing at the nix-built
     emulator binaries. Path layout differs per platform:
       - Linux:   <result>/bin/<emulator>
       - macOS:   <result>/Applications/<Name>.app/Contents/MacOS/<exe>

  2. es_systems.xml — derived from es_systems.template.xml with %LIBEXT%
     substituted to the platform's RetroArch core extension:
       - Linux:   .so
       - macOS:   .dylib

Both regenerate on every `make install` because nix store paths and core
extensions both vary by platform.
"""
import os
import sys


PLATFORM = {"darwin": "macos", "linux": "linux", "win32": "windows"}.get(sys.platform, "linux")
LIBEXT = {"linux": "so", "macos": "dylib", "windows": "dll"}[PLATFORM]


def _emulator_paths(result_dir: str) -> dict:
    """Per-platform emulator binary paths."""
    if PLATFORM == "macos":
        return {
            "RETROARCH": f"{result_dir}/Applications/RetroArch.app/Contents/MacOS/RetroArch",
            "AZAHAR":    f"{result_dir}/Applications/azahar.app/Contents/MacOS/azahar",
            "DOLPHIN":   f"{result_dir}/Applications/Dolphin.app/Contents/MacOS/Dolphin",
            "PCSX2":     f"{result_dir}/Applications/PCSX2.app/Contents/MacOS/PCSX2",
            "CEMU":      f"{result_dir}/Applications/Cemu.app/Contents/MacOS/Cemu",
            "RYUJINX":   os.path.expanduser(
                "~/.local/share/ryujinx-app/Ryujinx.app/Contents/MacOS/Ryujinx"
            ),
            "ARES":      f"{result_dir}/Applications/ares.app/Contents/MacOS/ares",
        }
    # Linux: standard FHS bin dir. Binary names match what the corresponding
    # nix derivation actually emits (verified against nix/*.nix in this repo
    # and the matching nixpkgs attributes). Round-2 critic finding #1.
    return {
        "RETROARCH": f"{result_dir}/bin/retroarch",
        "AZAHAR":    f"{result_dir}/bin/azahar",
        "DOLPHIN":   f"{result_dir}/bin/dolphin-emu",
        "PCSX2":     f"{result_dir}/bin/pcsx2-qt",
        "CEMU":      f"{result_dir}/bin/Cemu",         # nixpkgs cemu emits exact case 'Cemu'
        "RYUJINX":   f"{result_dir}/bin/ryujinx",      # our nix/ryujinx.nix:73 wrapper
        "ARES":      f"{result_dir}/bin/ares",
    }


def _retroarch_cores_dir(result_dir: str) -> str:
    if PLATFORM == "macos":
        return f"{result_dir}/cores"
    return f"{result_dir}/lib/retroarch/cores"


def _write_find_rules(result_dir: str, output_dir: str) -> str:
    emulators = _emulator_paths(result_dir)
    lines = [
        '<?xml version="1.0"?>',
        f"<!-- Generated by schemulator on {PLATFORM} - regenerated on each `make install` -->",
        "<ruleList>",
    ]
    for name, path in emulators.items():
        lines += [
            f'  <emulator name="{name}">',
            '    <rule type="staticpath">',
            f"      <entry>{path}</entry>",
            "    </rule>",
            "  </emulator>",
        ]
    lines += [
        '  <core name="RETROARCH">',
        '    <rule type="corepath">',
        f"      <entry>{_retroarch_cores_dir(result_dir)}</entry>",
        "    </rule>",
        "  </core>",
        "</ruleList>",
    ]
    path = os.path.join(output_dir, "es_find_rules.xml")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return path


def _write_systems_xml(repo_root: str, output_dir: str) -> str:
    """Substitute %LIBEXT% in the template and emit es_systems.xml."""
    template_path = os.path.join(repo_root, "ES-DE", "custom_systems", "es_systems.template.xml")
    if not os.path.exists(template_path):
        # Backwards-compat: if the template is missing, skip silently.
        return ""
    with open(template_path, encoding="utf-8") as f:
        rendered = f.read().replace("%LIBEXT%", LIBEXT)
    out_path = os.path.join(output_dir, "es_systems.xml")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(rendered)
    return out_path


def main():
    result_dir = os.path.realpath(sys.argv[1]) if len(sys.argv) > 1 else os.path.realpath("result")
    output_dir = os.path.expanduser("~/ES-DE/custom_systems")
    os.makedirs(output_dir, exist_ok=True)

    rules_path = _write_find_rules(result_dir, output_dir)
    print(f"  {rules_path}")

    repo_root = os.path.dirname(os.path.abspath(__file__))
    systems_path = _write_systems_xml(repo_root, output_dir)
    if systems_path:
        print(f"  {systems_path}  ({PLATFORM} → .{LIBEXT})")


if __name__ == "__main__":
    main()
